Habilita acesso à página informativa com base na coleção configurada na interface administrativa
scieloorg/opac_5 pull request #195
Opened 2024-10-15 18:08 UTC by samuelveigarangel

#### O que esse PR faz?
Habilita acesso à página informativa com base na coleção configurada na interface administrativa

#### Onde a revisão poderia começar?
pelos commits

#### Como este poderia ser testado manualmente?
Acessar página informativa

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
N/A

#### Quais são tickets relevantes?
#192 

### Referências
N/A

2024-10-31 12:34 UTC, gitnnolabs commented
@samuelveigarangel validando....

2024-10-31 16:35 UTC, gitnnolabs commented
@samuelveigarangel @robertatakenaka 

Validando essa atividade reparei que as páginas sobre o periódicos ficam com diversos seções com valores vazios, seria esse mesmo comportamento esperado? 

Vejam: 

![Screenshot 2024-10-31 at 13 33 42](https://github.com/user-attachments/assets/23c66ba3-d2b6-4598-97e7-d550bea4502c)

2024-10-31 16:40 UTC, gitnnolabs commented
Outro ponto interessante é que ao não temos conectividade com o https://core.scielo.org para obter a página apresentamos a seguinte página para usuário, veja: 

![Screenshot 2024-10-31 at 13 37 50](https://github.com/user-attachments/assets/00f72b04-ab27-4496-9de9-855b5294efb5)

Esse é um ponto de falha que podemos demorar para perceber, sugiro que seja apresentado uma página de erro mais amigável e que de alguma forma sejamos avisados.

Isso por ser uma melhoria!

2024-10-31 16:52 UTC, gitnnolabs commented
Reparei que ao trocar o idioma do site os labels não são alterado para o idioma apresentado: 

![Screenshot 2024-10-31 at 13 49 40](https://github.com/user-attachments/assets/967924e9-b880-48e2-a328-4dbc2942c028)

Repare que o idioma selecionado é o "Inglês" e os termos das seções estão em português.

2024-10-31 16:54 UTC, gitnnolabs requested changes
@samuelveigarangel verifica se é possível realizar os ajustes mencionados.

2024-11-04 12:04 UTC, samuelveigarangel commented
@gitnnolabs Esse comportamento dos campos vazios é esperado pois não há valor preenchido no formulário no core.

2024-11-04 12:04 UTC, samuelveigarangel commented
@gitnnolabs Não está traduzido pois não há os campos traduzidos nos arquivos de traduções no core.

2024-11-04 12:39 UTC, merged