Inclui novas variáveis de ambiente.
scieloorg/opac_5 pull request #196
Opened 2024-10-16 13:19 UTC by samuelveigarangel

#### O que esse PR faz?
Incluí novas váriaveis de ambiente.

#### Onde a revisão poderia começar?
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.

#### Como este poderia ser testado manualmente?
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.

#### Algum cenário de contexto que queira dar?
De acordo com Readme do projeto opac_5, foi incluído novas variáveis.

### Screenshots
N/A

#### Quais são tickets relevantes?
#184 
https://github.com/scieloorg/opac_5/issues/206

### Referências
N/A

2024-10-31 17:15 UTC, gitnnolabs commented
@samuelveigarangel @robertatakenaka sobre essa atividade tenho dúvida sobre a definição dela, me explico: 

É para termos todas as variáveis de ambientes na pasta .**envs**? ou é para termos as variáveis mais utilizadas? 

De fato olhando o PR e olhando os arquivos não temos todas as variáveis de ambiente no diretório .envs, exemplo: 

- GOOGLE_VERIFY_RECAPTCHA_KEY
- GOOGLE_RECAPTCHA_SECRET_KEY

Esse é um exemplo de variável que deve está em .envs pensado nos países é uma variável que deve ser trocada, cada país deve term sua conta de **recaptcha**.

A variável **DEFAULT_EMAIL** e **OPAC_EMAIL_ACCOUNTS_RECEIVE_ERRORS** são outros exemplos. 

Sugiro que todos as variáveis de ambiente estejam nesses arquivos da pasta **.envs** ou tenha um cabeçalho que indica as variáveis, assim com existe no arquivo **default.py** que indicar todas as variáveis de ambiente possíveis.

Vejam: https://github.com/scieloorg/opac_5/blob/master/opac/webapp/config/default.py#L6

2024-10-31 17:15 UTC, gitnnolabs requested changes

2024-11-12 13:34 UTC, robertatakenaka commented on docker-compose.yml
> +            - ./.envs/.production-template/.metrics
@samuelveigarangel manter `.production`

2024-11-12 13:35 UTC, robertatakenaka commented on docker-compose.yml
> +            - ./.envs/.production-template/.metrics
@samuelveigarangel o `.envs/.production` é para que ao baixar não sobrescreva o `.envs/.production` existente

2024-11-12 13:37 UTC, robertatakenaka commented on .envs/.production-template/.flask
> +# enables/disables the presentation of collection metrics data (default: False). Possible values: True or False
@samuelveigarangel adicionar o conteúdo de `.metrics` para `.flask`. Como `.metrics` e `.server` não são aplicações, a configuração deveria estar em `.flask`. @gitnnolabs o que acha?

2024-11-22 12:17 UTC, robertatakenaka commented on .envs/.production-template/.redis
> +OPAC_FORCE_USE_HTTPS_GOOGLE_TAGS
@samuelveigarangel faltou o `= com o valor default`

2024-11-22 12:21 UTC, robertatakenaka commented on .envs/.production-template/.server
> +OPAC_SESSION_COOKIE_DOMAIN=OPAC_SERVER_NAME
@samuelveigarangel o valor default não pode ser `OPAC_SERVER_NAME`

2024-12-09 13:38 UTC, gitnnolabs commented
Validando esse PR...

2024-12-10 14:43 UTC, gitnnolabs commented
Rodando localmente tive o seguinte erro: 


![Screenshot 2024-12-10 at 10 54 42](https://github.com/user-attachments/assets/67701c51-8f11-4246-8ad1-bf9499611b55)

Para resolver esse ponto é necessário somente envolver o valor de por aspas **"Creative Common - by 4.0"**

![Screenshot 2024-12-10 at 11 40 52](https://github.com/user-attachments/assets/c330e53d-bb74-4c06-9ac9-48170e204b97)



Percebi que está faltando as seguintes variáveis de ambiente nos arquivos **.envs**: 

```shell
MAIL_USERNAME = os.environ.get("OPAC_MAIL_USERNAME", None)
MAIL_PASSWORD = os.environ.get("OPAC_MAIL_PASSWORD", None)
MEDIA_URL = os.environ.get("OPAC_MEDIA_URL", "/media")
THUMBNAIL_HEIGHT = os.environ.get("THUMBNAIL_HEIGHT", 100)
THUMBNAIL_WIDTH = os.environ.get("THUMBNAIL_WIDTH", 100)
URL_SCIELO_ORG = os.environ.get("OPAC_URL_SCIELO_ORG", "//www.scielo.org")
URL_BLOG_SCIELO = os.environ.get("OPAC_URL_BLOG_SCIELO", "//blog.scielo.org")
URL_SEARCH = os.environ.get("OPAC_URL_SEARCH", "//search.scielo.org/")
URL_BLOG_PRESSRELEASE = os.environ.get("OPAC_URL_BLOG_PRESSRELEASE ", "//pressreleases.scielo.org")
USE_METRICS = os.environ.get("OPAC_USE_METRICS", "False") == "True"
METRICS_URL = os.environ.get("OPAC_METRICS_URL", "http://analytics.scielo.org")
USE_DIMENSIONS = os.environ.get("OPAC_USE_DIMENSIONS", "False") == "True"
DIMENSIONS_METRICS_URL = os.environ.get("OPAC_DIMENSIONS_METRICS_URL","https://badge.dimensions.ai/details/doi")
USE_PLUMX = os.environ.get("OPAC_USE_PLUMX", "False") == "True"
PLUMX_METRICS_URL = os.environ.get("OPAC_PLUMX_METRICS_URL", "https://plu.mx/scielo/a")
PLUMX_METRICS_JS = os.environ.get(
    "OPAC_PLUMX_METRICS_JS", "//cdn.plu.mx/widget-popup.js"
)
USE_ALTMETRIC = os.environ.get("OPAC_USE_ALTMETRIC", "False") == "True"
ALTMETRIC_METRICS_URL = os.environ.get(
    "OPAC_ALTMETRIC_METRICS_URL", "https://www.altmetric.com/details.php"
)
USE_SCIENCEOPEN = os.environ.get("OPAC_USE_SCIENCEOPEN", "False") == "True"
USE_SCITE = os.environ.get("OPAC_USE_SCITE", "False") == "True"
SCITE_URL = os.environ.get(
    "OPAC_SCITE_URL", "//cdn.scite.ai/badge/scite-badge-latest.min.js"
)
SCITE_METRICS_URL = os.environ.get(
    "OPAC_SCITE_METRICS_URL", "https://scite.ai/reports/"
)
ORCID_URL = os.environ.get("OPAC_ORCID_URL", "http://orcid.org/")
TWITTER_CONSUMER_KEY = os.environ.get("OPAC_TWITTER_CONSUMER_KEY", "")
TWITTER_CONSUMER_SECRET = os.environ.get("OPAC_TWITTER_CONSUMER_SECRET", "")
TWITTER_ACCESS_TOKEN = os.environ.get("OPAC_TWITTER_ACCESS_TOKEN", "")
TWITTER_ACCESS_TOKEN_SECRET = os.environ.get("OPAC_TWITTER_ACCESS_TOKEN_SECRET", "")
TWITTER_SCREEN_NAME = os.environ.get("OPAC_TWITTER_SCREEN_NAME", "RedeSciELO")
USE_SENTRY = os.environ.get("OPAC_USE_SENTRY", "False") == "True"
SENTRY_DSN = os.environ.get("OPAC_SENTRY_DSN", "")
BUILD_DATE = os.environ.get("OPAC_BUILD_DATE", None)
VCS_REF = os.environ.get("OPAC_VCS_REF", None)
WEBAPP_VERSION = os.environ.get("OPAC_WEBAPP_VERSION", None)
READCUBE_ENABLED = os.environ.get("OPAC_READCUBE_ENABLED", "False") == "True"SSM_XML_URL_REWRITE
HTML_GENERATOR_VERSION = os.environ.get("HTML_GENERATOR_VERSION", "3.0")
OPAC_SCHEME = os.environ.get("OPAC_OPAC_SCHEME", "https")
SEND_FILE_MAX_AGE_DEFAULT = os.environ.get("OPAC_SEND_FILE_MAX_AGE_DEFAULT", 604800)
CACHE_CONTROL_MAX_AGE_HEADER = os.environ.get(
    "OPAC_CACHE_CONTROL_MAX_AGE_HEADER", 604800
)
PINGDOM_VISITOR_INSIGHTS_JS_SRC = os.environ.get(
    "OPAC_PINGDOM_VISITOR_INSIGHTS_JS_SRC", None
)
SCIMAGO_URL = os.environ.get(
    "SCIMAGO_URL", "https://www.scimagojr.com/journalsearch.php?tip=sid&clean=0&q="
)
SCIMAGO_ENABLED = os.environ.get("SCIMAGO_ENABLED", "True") == "True"SCIMAGO_URL_IR
SCIMAGO_URL_IR = os.environ.get("SCIMAGO_URL_IR", "https://www.scimagoir.com/")MAILING_CRON_STRING
MAILING_CRON_STRING = os.environ.get("OPAC_MAILING_CRON_STRING", "0 7 * * *")
DEFAULT_SCHEDULER_TIMEOUT = int(os.environ.get("OPAC_DEFAULT_SCHEDULER_TIMEOUT", 1000))
MATHJAX_CDN_URL = os.environ.get("OPAC_MATHJAX_CDN_URL", DEFAULT_MATHJAX_CDN_URL)
OPAC_GOOGLE_SCHOLAR_LINK = os.environ.get(
    "OPAC_GOOGLE_SCHOLAR", "https://scholar.google.com/scholar?q="
)
OPAC_GOOGLE_LINK = os.environ.get("OPAC_GOOGLE", "https://www.google.com/search?q=")
APM_SERVICE_VERSION = os.environ.get("OPAC_APM_SERVICE_VERSION")
APM_FILTER_EXCEPTION_TYPES = os.environ.get("OPAC_APM_FILTER_EXCEPTION_TYPES")
APM_TRANSACTIONS_IGNORE_PATTERNS = os.environ.get(
    "OPAC_APM_TRANSACTIONS_IGNORE_PATTERNS"
)
APM_SERVER_TIMEOUT = os.environ.get("OPAC_APM_SERVER_TIMEOUT")
APM_HOSTNAME = os.environ.get("OPAC_APM_HOSTNAME")
APM_COLLECT_LOCAL_VARIABLES = os.environ.get("OPAC_APM_COLLECT_LOCAL_VARIABLES")
APM_LOCAL_VAR_MAX_LENGTH = os.environ.get("OPAC_APM_LOCAL_VAR_MAX_LENGTH")
APM_CAPTURE_BODY = os.environ.get("OPAC_APM_CAPTURE_BODY")
APM_CAPTURE_HEADERS = os.environ.get("OPAC_APM_CAPTURE_HEADERS", True)
APM_TRANSACTION_MAX_SPANS = os.environ.get("OPAC_APM_TRANSACTION_MAX_SPANS")
APM_STACK_TRACE_LIMIT = os.environ.get("OPAC_APM_STACK_TRACE_LIMIT")
APM_DEBUG = os.environ.get("OPAC_APM_DEBUG", False)
APM_DISABLE_SEND = os.environ.get("OPAC_APM_DISABLE_SEND", False)
APM_INSTRUMENT = os.environ.get("OPAC_APM_INSTRUMENT", True)
APM_VERIFY_SERVER_CERT = os.environ.get("OPAC_APM_APM_VERIFY_SERVER_CERT", True)
PREVIOUS_WEBSITE_URI = os.environ.get("PREVIOUS_WEBSITE_URI", "")
ALERT_MSG_PT = os.environ.get("ALERT_MSG_PT", "")
ALERT_MSG_EN = os.environ.get("ALERT_MSG_EN", "")
ALERT_MSG_ES = os.environ.get("ALERT_MSG_ES", "")
ALERT_MSG = bool(ALERT_MSG_PT or ALERT_MSG_EN or ALERT_MSG_ES)
ACCESSIBILITY_BY_LANGUAGE = {
    "pt_BR": os.environ.get(
        "ACCESSIBILITY_FORM_PT", "https://forms.gle/2Vpt2z26uGqHA7yy5"
    ),
    "en": os.environ.get(
        "ACCESSIBILITY_FORM_EN", "https://forms.gle/qHwovmddXdZRDxjm7"
    ),
    "es": os.environ.get(
        "ACCESSIBILITY_FORM_ES", "https://forms.gle/XZuJurSVMBp4E64j6"
    ),
}
CITATION_EXPORT_FORMATS = {"bib": "BibTex", "ris": "Reference Manager"}
```

Reparei que a variável **OPAC_CACHE_ENABLED**, está repetida em dois arquivos .**flask** e .**redis**

Sobre a variável de ambiente BABEL_DEFAULT_LOCALE, considerando que estamos instalando em outros países..... hoje ela que determina o valor padrão dos labels para tradução, mas isso é ruim... por que imagina a tradução será de português para qualquer idioma no passo nosso idioma não é universal como  o Inglês, isso é um ponto para o futuro.

``` 
BABEL_DEFAULT_LOCALE = "pt_BR"
```

A lista completa de variáveis em lista: 

```python 
[DEBUG, TESTING, LOG_LEVEL, ASSETS_DEBUG, MINIFY_PAGE, WEBMASTER_EMAIL, USE_HOME_METRICS, OPAC_COLLECTION, DEFAULT_EMAIL, EMAIL_ACCOUNTS_RECEIVE_ERRORS, MAIL_SERVER, MAIL_PORT, MAIL_USE_TLS, MAIL_USE_SSL, MAIL_DEBUG, MAIL_USERNAME, MAIL_PASSWORD, MAIL_DEFAULT_SENDER, MAIL_MAX_EMAILS, MAIL_ASCII_ATTACHMENTS, SECRET_KEY, MONGODB_NAME, MONGODB_HOST, MONGODB_PORT, MONGODB_USER, MONGODB_PASS, MONGODB_SETTINGS, DATABASE_FILE, DATABASE_DIR, DATABASE_PATH, SQLALCHEMY_DATABASE_URI, SQLALCHEMY_ECHO, SQLALCHEMY_TRACK_MODIFICATIONS, TOKEN_MAX_AGE, LANGUAGES, BABEL_DEFAULT_LOCALE, LOCAL_ZONE, GA_TRACKING_CODE, DEBUG_TB_INTERCEPT_REDIRECTS, DATA_PATH, JOURNAL_PAGES_ORIGINAL_WEBSITE, JOURNAL_PAGES_SOURCE_PATH, JOURNAL_IMAGES_SOURCE_PATH, DEFAULT_MEDIA_ROOT, MEDIA_ROOT, IMAGE_ROOT, FILE_ROOT, MEDIA_URL, FILES_ALLOWED_EXTENSIONS, IMAGES_ALLOWED_EXTENSIONS, IMAGES_ALLOWED_EXTENSIONS_RE, THUMBNAIL_HEIGHT, THUMBNAIL_WIDTH, URL_SCIELO_ORG, SCIELO_ORG_URIS, URL_BLOG_SCIELO, URL_SEARCH, URL_BLOG_PRESSRELEASE, USE_METRICS, METRICS_URL, USE_DIMENSIONS, DIMENSIONS_METRICS_URL, USE_PLUMX, PLUMX_METRICS_URL, PLUMX_METRICS_JS, USE_ALTMETRIC, ALTMETRIC_METRICS_URL, USE_SCIENCEOPEN, USE_SCITE, SCITE_URL, SCITE_METRICS_URL, ORCID_URL, NEWS_LIST_LIMIT, DEBUG_TB_PANELS, TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_TOKEN_SECRET, TWITTER_SCREEN_NAME, TWITTER_LIMIT, USE_SENTRY, SENTRY_DSN, BUILD_DATE, VCS_REF, WEBAPP_VERSION, OPAC_WTF_CSRF_ENABLED, OPAC_WTF_CSRF_SECRET_KEY, READCUBE_ENABLED [...]

2024-12-10 14:43 UTC, gitnnolabs requested changes
@samuelveigarangel verifique por gentileza meus comentários.

2024-12-10 20:22 UTC, gitnnolabs commented
Good job.

2024-12-10 20:22 UTC, gitnnolabs approved these changes

2024-12-10 20:22 UTC, merged